version: '2'
services:
    keygen:
        build: ./keygen
        volumes:
            - keys:/var/keys/
        entrypoint: /bin/true
        networks:
            - back-tier
    jenkins-server:
        build: ./jenkins
        volumes:
            - keys:/var/keys/
            - data:/var/jenkins_home/
        expose:
            - "8080"
            - "50000"
        environment:
            - JAVA_OPTS="-Djenkins.install.runSetupWizard=false"
        networks:
            - back-tier
    jenkins-slave1:
        build: ./jenkins-slave
        volumes:
            - keys:/var/keys/
        networks:
            - back-tier
    www:
        build: ./www
        ports:
            - "80:80"
        depends_on:
            - jenkins-server
        networks:
            - back-tier
volumes:
  data:
    driver: nfs
    driver_opts:
        share: "core-01:/exports"
  keys:
    driver: nfs
    driver_opts:
        share: "core-01:/exports"
networks:
  back-tier:
    driver: overlay